#cloud-config

coreos:
  fleet:
    metadata: "role=worker"
    etcd_servers: "http://10.240.20.133:4001"
  locksmith:
    endpoint: "http://10.240.20.133:4001"
  units:
    - name: etcd2.service
      mask: true
    - name: fleet.service
      command: start
users:
  - name: fedot
    groups:
      - sudo
      - docker
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDSdF9ETDpypv0D2bwUgqwlKxbpPEHgfH9Psuav/a5fSraj+CS54HnTycDSzrrMX4STHm0cFFeA2SzDbJGVDWWpOOhr+o4zMwY9uwW+5gjtDRf/wKFACIJhLRv5tHx4Z7TBsaiLHpzi8l7gHIh/gxGISw6TpRhg5JC9dYJGoTyIL2muo3/l1q+gr/ASOInL7pcUcJaWrjFYO9cgl4wFbqeIKBy8TxvKyOO7GV6eU8qUoG7QjhHjZiWECbIe7q6smWukF9tZXD5sAtCrblEOO8NXDxUwfee4qESgwu+0OD17m0xxXU+wALEWVeM420g6bQknvYj3EjlQkeyjhC+p5nZH fedot@fedot.home
write_files:
  - path: /etc/profile.d/etcdctl.sh
    permissions: 0644
    owner: core
    content: |
      # configure etcdctl to work with our etcd servers set above
      export ETCDCTL_PEERS="http://10.240.20.133:4001"
  - path: /etc/profile.d/fleetctl.sh
    permissions: 0644
    owner: core
    content: |
      # configure fleetctl to work with our etcd servers set above
      export FLEETCTL_ENDPOINT=unix:///var/run/fleet.sock
      export FLEETCTL_EXPERIMENTAL_API=true
  - path: /etc/environment-for-container
    permissions: 0644
    owner: core
    content: |
      MONGODB_HOST="10.240.20.133"
  - path: /home/core/.dockercfg
    owner: core
    content: |
      {
        "https://index.docker.io/v1/": {
          "email": "fedotru@gmail.com",
          "auth": "ZmVkb3Q6WkVOSVRESg=="
        }
      }